application:
  subdomain: briefing
  background_task: true
  multi_instance: false
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://briefing:8080/

services:
  briefing:
    # upstream: holtwick/briefing:3.1.10
    image: holtwick/briefing:3.1.10
    binds:
      - /lzcapp/var/data:/app/data
